### ISSUE TITLE
Mark homework 1, exercise 3 of Kun-Chieh Wang

### ISSUE THREAD

**Issue by kunchieh** [kunchieh/stat679work#5]
@cecileane

https://github.com/kunchieh/stat679work/commit/461ac45c4f72959a25727f29cd1b3e82eedf4baf

HW1-3 submission

**Comment by rebeccapost** [comment]
I think your code could be more efficient if all of the ggreps were changed to sed, since then we do not have to pipe through multiple functions. In addition, by using sed you could avoid having to figure out how many lines to pull in head.

Your ggreps are very succinct, which I think look nice and help draw the eye to the important key words in the files you are searching.

A comment about the output: Since we are outputting a table, it might be nice for a user to have headings. You could do this by adding a line that just echos the variable names(no $) to the file first.

I thought your comment section at the top was very descriptive and provided good detail about what was going to happen in the script.

In addition, I thought it was clever to save the output file as a variable so that if you decide to change the file name you do not need to go through and edit each output line.

At the end where you write each variable to the output file though, if you had used echo followed by each variable name (separated by a comma) and then >> output, you could have reduced those 13 lines of code into 1. I am not sure if this is more efficient or not, but it is an idea to consider.

Overall your code is nicely organized and well done!

**Comment by WangTJ** [comment]
Hi, 
Sorry for the late reply. 
I think you use "ggrep" nice and clear. Exercise 3 asks us to try more command like "sed" and "cut". It will be better if you try them in your code.
I agree with Rebecca about your output. It might be nice to have headings for the columns. And, since we mainly learn "echo" in the course as a standard output command, it will be better if you use  it in your code.
Your comment section is clear and rich. It helps me a lot in my reading process.
Your repository's "readme" files are brief and clear, describe what you update in this issue. But it will be better if you make more subdirectories like "src" to make the files neater.
When you use git commit, you can leave some comments to describe what you update with more details.

Overall, your code is beautiful and works well.

TJ
