### ISSUE TITLE
Mark homework 2 of Kun-Chieh Wang

### ISSUE THREAD

**Issue by kunchieh** [kunchieh/stat679work#7]
@cecileane

https://github.com/kunchieh/stat679work/commit/22933006c458fe20d766b306ecd9f3ce53cce584

HW2 submission. I might have misunderstanding and make a fatal error into just a warning. Could you please inform me if you see anything that should be a fatal error in your opinion?

**Comment by cecileane** [comment]
Hi Jason,

Very nice job! Your work was easy to go through, and your script worked. More details below.

## overall presentation

It is best to organize your project with different directories for scripts, input / output files etc. Yes, this project had very few files, but it's a good habit to get into.

Your readme file could do a better use of the markdown syntax. For example, your list of file requirements (which is absolutely great to have by the way) is all in one single block of code. Instead, you should have used marks to make your numbered list and your unordered lists, etc.

(you still have a `.DS_Store` file tracked by git!)

## running your script

Getting help worked great, it made using the script very easy.
I love the feature that creates a log file listing warnings. Unfortunately, the line that said warnings popped was sent to stdout, not stderr, so it is mixed with the csv output that is also sent to the stdout:

```shell
$ python hw2.py -t waterTemperature.csv -e energy.csv > myout.csv
$ tail -n 3 myout.csv
362,08/13/16 11:26:34 AM,73.06,
363,08/13/16 12:26:34 PM,76.39,
Warning pops: check summary.log for more details
```

To print to stderr instead of stdout, you would replace (line 142) `print("message")` by `sys.stderr.write("message\n")` (or use the `warnings` module).

In the output file, the header row is missing something for the last column, with the energy data (like "Energy Produced (kWh/1000)"). 

## about your code

It's very well organized: broken down into functions, with comments for important sections of code. You check for a bunch of things, which is great. Your docstrings (to document your functions) could say a little more about what the function arguments are. It looks like they are file handles, already opened for reading/writing, and not file names. This is not intuitive, so it's best to document that. You could have some more comments inside the code, to explain a little about the algorithm, near that lines that do each step.

Great job overall!
